before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bash ./scripts/validate-tests.sh
install:
  - yarn
after_success:
  - bash ./scripts/docs-upload-gh.sh
branches:
  only:
    - master
    - /^release\/.*$/
env:
  global:
    - secure: "Recue3+sPDb4kQtKftZuYa0zwg6/+H+QO5tJP8WGa+Xq7OZBGzAt/bADW0Q7KvUPxtK6qUCynuWrnaBlEWc+UKIHlrcHCpFPn0zkpzGvzX6a+tvhjHAQNDB7x/VYORvYEQqMzWC5t+qLj6C9ffjXP+6uCo+o+y/5K5ydEyqa2e42LQblSJmiiCG754CqV1LxmasklGAC90+ldR6d7PFFpqXDc/BIsyDAIuS4FXfjyli+VnvCza7PQJ4XGkCoywmBNg8bcR82UwduA854/Gr7oYKZRUamMpBuQY25EupjwZ/GV2OyDSK3UcO3blEVrjRnP3gC9Ljd+WvcBqy7d1FJTCk0Vsy/pstxjVpP19H3I6xOU41buB3Pw1aLTkIp+PFmhoab5fu03bWfwUp/N1Xl1URKWcIKokwh/98NSA8OZ16VbMhFkxuUCs5bsFR+DB6SLdc2XNpzzdxdoe3XZHB5LxVOIoJY6CiskfYdNBPsEo+NZTrv+eUk+l4gMNTIYwgCWEbbIvXE6CwFITg9ERQhY7fvGJ37DOWfvLfxKnDc0jFqnlUnWgrtDppx7akE1vgfFu9W8jWRF4phGU/O4BwWUNhLtoGUgTH6RR4+4xoNv3LB1g6fnd50jUin4f6o2KSOkdPZFPmv74MygC7WyPERWR2IjpT2x+yfPIa6TetlY/c="
language: node_js
node_js:
  - "6"
cache:
  directories:
  - $HOME/.yarn-cache
